// Copyright (c) 2025 Ekkodale GmbH. All rights reserved.
//
// This file is part of the gaeco platform system.
//
// Use of this file is governed by the terms of the license
// in LICENSE.md at the root of this repository.
// Unauthorized copying, modification, distribution, or use of this file,
// via any medium, is strictly prohibited except as expressly permitted
// under that license.

using AppOrchestrator.Api.Services._Interfaces.Docker;
using FastEndpoints;
using FluentValidation;

namespace AppOrchestrator.Api.Endpoints.ContainerRegistries;

/// <summary>
/// Request payload for testing container registry credentials without persisting a registry entry.
/// </summary>
public class TestContainerRegistryRequest
{
    /// <summary>
    /// Registry host name or URL used by Docker login.
    /// </summary>
    public string ServerAddress { get; set; } = string.Empty;

    /// <summary>
    /// Username for the login probe.
    /// </summary>
    public string Username { get; set; } = string.Empty;

    /// <summary>
    /// Password or token for the login probe.
    /// </summary>
    public string Password { get; set; } = string.Empty;
}

/// <summary>
/// Validates test-container-registry payload rules.
/// </summary>
public class TestContainerRegistryValidator : Validator<TestContainerRegistryRequest>
{
    public TestContainerRegistryValidator()
    {
        RuleFor(x => x.ServerAddress).NotEmpty().MaximumLength(500).Matches(@"^https?://|^[^/\s]+$").WithMessage("Server address must be a valid hostname or URL.");
        RuleFor(x => x.Username).NotEmpty();
        RuleFor(x => x.Password).NotEmpty();
    }
}

/// <summary>
/// Result payload of a registry credential probe.
/// </summary>
public class TestContainerRegistryResponse
{
    /// <summary>
    /// Indicates whether docker login succeeded.
    /// </summary>
    public bool Success { get; set; }

    /// <summary>
    /// Human-readable outcome message returned by Docker or generated by the API.
    /// </summary>
    public string Message { get; set; } = string.Empty;
}

/// <summary>
/// Tests container registry credentials by executing login and immediate logout.
/// </summary>
public class TestContainerRegistry(IDockerRegistryService dockerRegistryService)
    : Endpoint<TestContainerRegistryRequest, TestContainerRegistryResponse>
{
    public override void Configure()
    {
        Post("container-registries/test");
        Summary(s =>
        {
            s.Summary = "Test container registry credentials.";
            s.Description = "Executes docker login with the provided credentials and, on success, docker logout. No registry entity is persisted. This endpoint is intended for pre-validation in client forms.";
            s.Response<TestContainerRegistryResponse>(200, "Credential test result including success flag and message.");
            s.Response(401, "The caller is not authenticated.");
        });
    }

    public override async Task HandleAsync(TestContainerRegistryRequest req, CancellationToken ct)
    {
        var (success, output) = await dockerRegistryService.TestRegistryAsync(
            req.ServerAddress,
            req.Username,
            req.Password,
            ct);

        await SendOkAsync(new TestContainerRegistryResponse
        {
            Success = success,
            Message = success ? "Login successful." : output
        }, ct);
    }
}

