// <auto-generated />
using System;
using AppOrchestrator.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppOrchestrator.Infrastructure.Migrations
{
    [DbContext(typeof(AppOrchestratorDbContext))]
    [Migration("20260325225206_RemovePluginHostsTable")]
    partial class RemovePluginHostsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppOrchestrator.Domain.Models.AppRegistry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BaseUrl")
                        .IsUnique();

                    b.ToTable("AppRegistries");
                });

            modelBuilder.Entity("AppOrchestrator.Domain.Models.ContainerRegistry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ServerAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ServerAddress")
                        .IsUnique();

                    b.ToTable("ContainerRegistries");
                });

            modelBuilder.Entity("AppOrchestrator.Domain.Models.Network", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Name");

                    b.ToTable("Networks");
                });

            modelBuilder.Entity("AppOrchestrator.Domain.Models.Stack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DockerProjectName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("StackName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("StackType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DockerProjectName")
                        .IsUnique();

                    b.HasIndex("NetworkName");

                    b.ToTable("Stacks");

                    b.HasDiscriminator<string>("StackType").HasValue("Stack");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AppOrchestrator.Domain.Models.CustomStack", b =>
                {
                    b.HasBaseType("AppOrchestrator.Domain.Models.Stack");

                    b.HasDiscriminator().HasValue("Custom");
                });

            modelBuilder.Entity("AppOrchestrator.Domain.Models.RegistryStack", b =>
                {
                    b.HasBaseType("AppOrchestrator.Domain.Models.Stack");

                    b.Property<Guid>("AppRegistryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasIndex("AppRegistryId");

                    b.HasDiscriminator().HasValue("Registry");
                });

            modelBuilder.Entity("AppOrchestrator.Domain.Models.Network", b =>
                {
                    b.OwnsMany("AppOrchestrator.Domain.Models.EnvironmentVariable", "EnvironmentVariables", b1 =>
                        {
                            b1.Property<string>("NetworkName")
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.HasKey("NetworkName", "Id");

                            b1.ToTable("EnvironmentVariable");

                            b1.WithOwner()
                                .HasForeignKey("NetworkName");
                        });

                    b.Navigation("EnvironmentVariables");
                });

            modelBuilder.Entity("AppOrchestrator.Domain.Models.Stack", b =>
                {
                    b.HasOne("AppOrchestrator.Domain.Models.Network", "Network")
                        .WithMany("Stacks")
                        .HasForeignKey("NetworkName")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Network");
                });

            modelBuilder.Entity("AppOrchestrator.Domain.Models.RegistryStack", b =>
                {
                    b.HasOne("AppOrchestrator.Domain.Models.AppRegistry", "AppRegistry")
                        .WithMany("Stacks")
                        .HasForeignKey("AppRegistryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppRegistry");
                });

            modelBuilder.Entity("AppOrchestrator.Domain.Models.AppRegistry", b =>
                {
                    b.Navigation("Stacks");
                });

            modelBuilder.Entity("AppOrchestrator.Domain.Models.Network", b =>
                {
                    b.Navigation("Stacks");
                });
#pragma warning restore 612, 618
        }
    }
}
